### ISSUE TITLE
Cannot find AlamofireReactive

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveGitter#1]
Cannot find AlamofireReactive when `pod install`

``` shell
~/ReactiveKit/ReactiveGitter $ pod install
Analyzing dependencies
[!] Unable to find a specification for `AlamofireReactive (~> 1.0)`
```

**Comment by jechol** [comment]
Resolved after updating pod repository update, `pod repo update`

**Comment by srdanrasic** [comment]
Ah, great :) Btw, if you are experiencing "None of your spec sources contain a spec satisfying the dependencies: `ReactiveKit (~> 2.0), ReactiveKit (= 2.0.0)`.", try again. I **just** fixed that. Issue was in spec of ReactiveUIKit.

**Comment by srdanrasic** [comment]
Thanks for reporting this. I'll close it now.
