### ISSUE TITLE
JSON decode error

### ISSUE THREAD

**Issue by jechol** [ReactiveKit/ReactiveGitter#2]
After login to Gitter via Github account, following error occurred.

<img src="https://cloud.githubusercontent.com/assets/795125/15463568/4ec496ac-2105-11e6-9674-e13e43205600.png" width="400px">

**Comment by srdanrasic** [comment]
In API/Room.swift, if you make `uri` optional String, does it help?

**Comment by jechol** [comment]
Yes! But another error occurred.

Console output is following.

```
Operation at /Users/jechol/study/ReactiveKit/ReactiveGitter/Home/Director.swift:52 encountered an error: JSONDecodableError: Missing value for key lastAccessTime
```

**Comment by srdanrasic** [comment]
I guess `lastAccessTime` should also be optional :)

Interestingly, I wasn't getting those errors. I guess it differes depending on what rooms you've joined. But I would never expect `uri` to be optional...
