### ISSUE TITLE
Request: step by step guide?

### ISSUE THREAD

**Issue by Erkened** [ReactiveKit/ReactiveGitter#4]
If you have some time and it's not too much trouble, would it be possible to get something like a step by step guide of ReactiveGitter? I personally would find it really interesting to understand the logic behind the code. What code you wrote first, and how everything went from there. Of course if this is too much asking I'll just close this request.

**Comment by srdanrasic** [comment]
Here you go https://medium.com/hacker-daily/a-pragmatic-functional-reactive-architecture-with-swift-1e564cdbb1a4 :)
