### ISSUE TITLE
Unable to build project in Xcode 8.3

### ISSUE THREAD

**Issue by rnine** [ReactiveKit/ReactiveGitter#5]
The following code in `AppDelegate.swift` does not seem to compile in Xcode 8.3, failing with: `Type of expression is ambiguous without more context`:

```
        scene.logOut.bind(to: tokenService) { tokenService, _ in
          tokenService.updateToken(nil)
        }
```

and

```
        scene.tokenAcquired.bind(to: tokenService) { tokenService, token in
          tokenService.updateToken(token)
        }
```

**Comment by frederic-c-dcode** [comment]
@rnine have you found a workaround ?

**Comment by rnine** [comment]
@frederic-c-evo Unfortunately not!

**Comment by srdanrasic** [comment]
Hi guys, I'll try to update the demo project over the weekend. It hasn't really been kept up to date.

**Comment by rnine** [comment]
@srdanrasic OK, looking forward to it! 👍

**Comment by srdanrasic** [comment]
Should be working now @rnine, @frederic-c-evo! Thanks for waiting :)

**Comment by rnine** [comment]
@srdanrasic Thanks! :)
